ALTER TABLE crm.outbox_events
    ADD COLUMN IF NOT EXISTS sequence_id bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS crm_outbox_tenant_sequence_idx
    ON crm.outbox_events (tenant_id, sequence_id);