-- Complete the admin-web access catalog for every module and feature that the
-- current mobile student portal can render from ModuleCatalog.

INSERT INTO authz.permission_templates
    (permission_key, module_key, feature_key, action, crud_actions, display_name, description, active)
SELECT permission_key, module_key, feature_key, action, crud_actions, display_name, description, true
FROM (VALUES
    ('examination.config.create', 'examination', 'config', 'create', ARRAY['create']::text[], 'Create exam configuration', 'Create examination configuration'),
    ('examination.config.read', 'examination', 'config', 'read', ARRAY['read']::text[], 'View exam configuration', 'View examination configuration'),
    ('examination.config.update', 'examination', 'config', 'update', ARRAY['update']::text[], 'Update exam configuration', 'Update examination configuration'),
    ('examination.scheduling.create', 'examination', 'scheduling', 'create', ARRAY['create']::text[], 'Create exam schedule', 'Create examination schedules'),
    ('examination.scheduling.update', 'examination', 'scheduling', 'update', ARRAY['update']::text[], 'Update exam schedule', 'Update examination schedules'),
    ('examination.scheduling.publish', 'examination', 'scheduling', 'publish', ARRAY['update']::text[], 'Publish exam schedule', 'Publish examination schedules'),
    ('examination.eligibility.approve', 'examination', 'eligibility', 'approve', ARRAY['update']::text[], 'Approve exam eligibility', 'Approve examination eligibility'),
    ('examination.conduct.create', 'examination', 'conduct', 'create', ARRAY['create']::text[], 'Create exam conduct record', 'Create examination conduct and incident records'),
    ('examination.conduct.read', 'examination', 'conduct', 'read', ARRAY['read']::text[], 'View exam conduct', 'View examination conduct and incident records'),
    ('examination.conduct.update', 'examination', 'conduct', 'update', ARRAY['update']::text[], 'Update exam conduct', 'Update examination conduct and incident records'),
    ('examination.marks.create', 'examination', 'marks', 'create', ARRAY['create']::text[], 'Create marks entry', 'Create examination marks entries'),
    ('examination.marks.read', 'examination', 'marks', 'read', ARRAY['read']::text[], 'View marks entry', 'View examination marks entries'),
    ('examination.marks.update', 'examination', 'marks', 'update', ARRAY['update']::text[], 'Update marks entry', 'Update examination marks entries'),
    ('examination.moderation.read', 'examination', 'moderation', 'read', ARRAY['read']::text[], 'View moderation', 'View examination moderation'),
    ('examination.moderation.approve', 'examination', 'moderation', 'approve', ARRAY['update']::text[], 'Approve moderation', 'Approve examination moderation'),
    ('examination.moderation.update', 'examination', 'moderation', 'update', ARRAY['update']::text[], 'Update moderation', 'Update examination moderation'),
    ('examination.grades.approve', 'examination', 'grades', 'approve', ARRAY['update']::text[], 'Approve grades', 'Approve grades and GPA'),
    ('examination.degree_audit.read', 'examination', 'degree_audit', 'read', ARRAY['read']::text[], 'View degree audit', 'View degree audit'),
    ('examination.degree_audit.approve', 'examination', 'degree_audit', 'approve', ARRAY['update']::text[], 'Approve degree audit', 'Approve degree audit'),
    ('examination.publishing.approve', 'examination', 'publishing', 'approve', ARRAY['update']::text[], 'Approve result publishing', 'Approve result publishing'),
    ('examination.publishing.publish', 'examination', 'publishing', 'publish', ARRAY['update']::text[], 'Publish results', 'Publish examination results'),
    ('examination.transcript.create', 'examination', 'transcript', 'create', ARRAY['create']::text[], 'Create transcript', 'Create examination transcripts'),
    ('examination.ai_insights.read', 'examination', 'ai_insights', 'read', ARRAY['read']::text[], 'View AI exam insights', 'View AI examination insights'),

    ('timetable.schedule.create', 'timetable', 'schedule', 'create', ARRAY['create']::text[], 'Create timetable', 'Create class timetable schedules'),
    ('timetable.schedule.update', 'timetable', 'schedule', 'update', ARRAY['update']::text[], 'Update timetable', 'Update class timetable schedules'),
    ('timetable.schedule.delete', 'timetable', 'schedule', 'delete', ARRAY['delete']::text[], 'Delete timetable', 'Delete class timetable schedules'),
    ('timetable.config.create', 'timetable', 'config', 'create', ARRAY['create']::text[], 'Create timetable configuration', 'Create timetable configuration'),
    ('timetable.config.read', 'timetable', 'config', 'read', ARRAY['read']::text[], 'View timetable configuration', 'View timetable configuration'),
    ('timetable.config.update', 'timetable', 'config', 'update', ARRAY['update']::text[], 'Update timetable configuration', 'Update timetable configuration'),
    ('timetable.substitution.create', 'timetable', 'substitution', 'create', ARRAY['create']::text[], 'Create substitution', 'Create timetable substitutions'),
    ('timetable.substitution.approve', 'timetable', 'substitution', 'approve', ARRAY['update']::text[], 'Approve substitution', 'Approve timetable substitutions'),
    ('timetable.publication.approve', 'timetable', 'publication', 'approve', ARRAY['update']::text[], 'Approve timetable publication', 'Approve timetable publications'),
    ('timetable.publication.publish', 'timetable', 'publication', 'publish', ARRAY['update']::text[], 'Publish timetable', 'Publish timetable changes'),

    ('attendance.roster.update', 'attendance', 'roster', 'update', ARRAY['update']::text[], 'Update attendance roster', 'Update attendance roster'),

    ('tuition_fee.invoice.create', 'tuition_fee', 'invoice', 'create', ARRAY['create']::text[], 'Create fee invoice', 'Create tuition fee invoices'),

    ('academics.programme.create', 'academics', 'programme', 'create', ARRAY['create']::text[], 'Create programme', 'Create academic programmes'),
    ('academics.programme.update', 'academics', 'programme', 'update', ARRAY['update']::text[], 'Update programme', 'Update academic programmes'),
    ('academics.subject.create', 'academics', 'subject', 'create', ARRAY['create']::text[], 'Create subject', 'Create academic subjects'),
    ('academics.subject.update', 'academics', 'subject', 'update', ARRAY['update']::text[], 'Update subject', 'Update academic subjects'),

    ('vendor_management.vendors.create', 'vendor_management', 'vendors', 'create', ARRAY['create']::text[], 'Create vendor', 'Create vendor directory records'),
    ('vendor_management.vendors.read', 'vendor_management', 'vendors', 'read', ARRAY['read']::text[], 'View vendors', 'View vendor directory records'),
    ('vendor_management.vendors.update', 'vendor_management', 'vendors', 'update', ARRAY['update']::text[], 'Update vendor', 'Update vendor directory records'),
    ('vendor_management.contracts.create', 'vendor_management', 'contracts', 'create', ARRAY['create']::text[], 'Create contract', 'Create vendor contracts and AMCs'),
    ('vendor_management.contracts.read', 'vendor_management', 'contracts', 'read', ARRAY['read']::text[], 'View contracts', 'View vendor contracts and AMCs'),
    ('vendor_management.contracts.update', 'vendor_management', 'contracts', 'update', ARRAY['update']::text[], 'Update contract', 'Update vendor contracts and AMCs'),
    ('vendor_management.purchase_orders.create', 'vendor_management', 'purchase_orders', 'create', ARRAY['create']::text[], 'Create purchase order', 'Create vendor purchase orders'),
    ('vendor_management.purchase_orders.read', 'vendor_management', 'purchase_orders', 'read', ARRAY['read']::text[], 'View purchase orders', 'View vendor purchase orders'),
    ('vendor_management.purchase_orders.approve', 'vendor_management', 'purchase_orders', 'approve', ARRAY['update']::text[], 'Approve purchase order', 'Approve vendor purchase orders'),
    ('vendor_management.payments.create', 'vendor_management', 'payments', 'create', ARRAY['create']::text[], 'Create vendor payment', 'Create vendor payments'),
    ('vendor_management.payments.read', 'vendor_management', 'payments', 'read', ARRAY['read']::text[], 'View vendor payments', 'View vendor payments and history'),
    ('vendor_management.payments.approve', 'vendor_management', 'payments', 'approve', ARRAY['update']::text[], 'Approve vendor payment', 'Approve vendor payments'),
    ('vendor_management.work_orders.create', 'vendor_management', 'work_orders', 'create', ARRAY['create']::text[], 'Create work order', 'Create vendor work orders'),
    ('vendor_management.work_orders.read', 'vendor_management', 'work_orders', 'read', ARRAY['read']::text[], 'View work orders', 'View vendor work orders'),
    ('vendor_management.work_orders.update', 'vendor_management', 'work_orders', 'update', ARRAY['update']::text[], 'Update work order', 'Update vendor work orders')
) AS permission(permission_key, module_key, feature_key, action, crud_actions, display_name, description)
ON CONFLICT (permission_key) DO UPDATE SET
    module_key = EXCLUDED.module_key,
    feature_key = EXCLUDED.feature_key,
    action = EXCLUDED.action,
    crud_actions = EXCLUDED.crud_actions,
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    active = true,
    updated_at = now();

INSERT INTO authz.permission_definitions
    (tenant_id, permission_key, module_key, feature_key, action, crud_actions,
     display_name, description, active)
SELECT tenant.id, template.permission_key, template.module_key, template.feature_key,
       template.action, template.crud_actions, template.display_name, template.description, true
FROM platform.tenants AS tenant
JOIN authz.permission_templates AS template
  ON template.permission_key IN (
    'examination.config.create',
    'examination.config.read',
    'examination.config.update',
    'examination.scheduling.create',
    'examination.scheduling.update',
    'examination.scheduling.publish',
    'examination.eligibility.approve',
    'examination.conduct.create',
    'examination.conduct.read',
    'examination.conduct.update',
    'examination.marks.create',
    'examination.marks.read',
    'examination.marks.update',
    'examination.moderation.read',
    'examination.moderation.approve',
    'examination.moderation.update',
    'examination.grades.approve',
    'examination.degree_audit.read',
    'examination.degree_audit.approve',
    'examination.publishing.approve',
    'examination.publishing.publish',
    'examination.transcript.create',
    'examination.ai_insights.read',
    'timetable.schedule.create',
    'timetable.schedule.update',
    'timetable.schedule.delete',
    'timetable.config.create',
    'timetable.config.read',
    'timetable.config.update',
    'timetable.substitution.create',
    'timetable.substitution.approve',
    'timetable.publication.approve',
    'timetable.publication.publish',
    'attendance.roster.update',
    'tuition_fee.invoice.create',
    'academics.programme.create',
    'academics.programme.update',
    'academics.subject.create',
    'academics.subject.update',
    'vendor_management.vendors.create',
    'vendor_management.vendors.read',
    'vendor_management.vendors.update',
    'vendor_management.contracts.create',
    'vendor_management.contracts.read',
    'vendor_management.contracts.update',
    'vendor_management.purchase_orders.create',
    'vendor_management.purchase_orders.read',
    'vendor_management.purchase_orders.approve',
    'vendor_management.payments.create',
    'vendor_management.payments.read',
    'vendor_management.payments.approve',
    'vendor_management.work_orders.create',
    'vendor_management.work_orders.read',
    'vendor_management.work_orders.update'
  )
WHERE template.active
ON CONFLICT (tenant_id, permission_key) DO UPDATE SET
    module_key = EXCLUDED.module_key,
    feature_key = EXCLUDED.feature_key,
    action = EXCLUDED.action,
    crud_actions = EXCLUDED.crud_actions,
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    active = true,
    updated_at = now();
