[package]
name = "supercampus-platform-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
dotenvy.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
uuid.workspace = true
supercampus-authn = { path = "../../crates/authn" }
supercampus-observability.workspace = true
supercampus-database = { path = "../../crates/database" }
supercampus-crm = { path = "../../modules/crm" }

[dev-dependencies]
tower.workspace = true