[package]
name = "supercampus-notifications"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
lettre.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
